; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

	TITLE	c:\users\scott burgert\documents\actual projects\xsb web ide\analysis\compiler\compiler\compiler\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
; Function compile flags: /Ogtp
;	COMDAT ?function@@YAXXZ
_TEXT	SEGMENT
?function@@YAXXZ PROC					; function, COMDAT
; File C:\Users\Scott Burgert\Documents\Actual Projects\XSB Web IDE\Analysis\Compiler\Compiler\Compiler\StaticTest.h
; Line 6
	ret	0
?function@@YAXXZ ENDP					; function
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File C:\Users\Scott Burgert\Documents\Actual Projects\XSB Web IDE\Analysis\Compiler\Compiler\Compiler\Main.cpp
; Line 7
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
