; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

	TITLE	c:\users\scott burgert\documents\actual projects\xsb web ide\analysis\compiler\compiler\compiler\math.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

END
